version: "3.7"

volumes:
  sample-log-monitoring-vol:
    name: sample-log-monitoring-vol

networks:
  sample-log-monitoring:
    name: sample-log-monitoring-net

services:  
  ####################################
  # API
  ####################################
  sample-log-monitoring-api:
    build: .
    image: sample-log-monitoring/api:1.0
    container_name: sample-log-monitoring-api
    ports:
      - 3000:3000
    networks:
      - sample-log-monitoring

  ####################################
  # KONG API GATEWAY
  ####################################
  # pubsub-apigw:
  #   build: services/apigw/kong
  #   image: pubsub/apigw:1.0
  #   container_name: pubsub-apigw
  #   volumes:
  #     - apigw-vol
  #   environment:
  #     KONG_DATABASE: 'off'
  #     KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: '0.0.0.0:8001'      
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #   networks:
  #     - pubsub
  #   ports:
  #     - "8000:8000/tcp"
  #     - "127.0.0.1:8001:8001/tcp"
  #   healthcheck:
  #     test: ["CMD", "kong", "health"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #   restart: on-failure
  #   deploy:
  #     restart_policy:
  #       condition: on-failure


  ####################################
  # ELASTIC
  ####################################
  sample-log-monitoring-search:
    build: services/elastic
    image:  sample-log-monitoring/elastic:1.0
    container_name: sample-log-monitoring-search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - sample-log-monitoring

  ####################################
  # KIBANA
  ####################################
  sample-log-monitoring-viz:
    build: services/kibana
    image:  sample-log-monitoring/kibana:1.0
    container_name: sample-log-monitoring-viz
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.sample-log-monitoring.org
      ELASTICSEARCH_HOSTS: http://sample-log-monitoring-search:9200
    depends_on:
      - sample-log-monitoring-search
    networks:
      - sample-log-monitoring

  ####################################
  # FLUENTD
  ####################################
  sample-log-monitoring-fluentd:
    build: services/fluentd
    image:  sample-log-monitoring/fluentd:1.0
    container_name: sample-log-monitoring-fluentd
    ports:
      - 9880:9880
      - 24224:24224
    environment:
      FLUENTD_CONF: fluentd.conf
    networks:
      - sample-log-monitoring